### PR TITLE
Support +python3

### PR DESCRIPTION
**Pull request by wkentaro**
I sometimes use vim with +python3 without +python (on my macOS), and if I load my .vimrc in that environment there is the error.
This PR is necessary to fix it.

### CODE REVIEW

**Comment by taketwo** [comment]
Hi Kentaro, thanks for the patches. I cherry-picked your first commit into the master already. The second, however, I can not apply as is. There are two problems:

1. When using Python3, the commands in ["autoload/vim.ros"](https://github.com/taketwo/vim-ros/blob/master/autoload/ros.vim#L15) should be using `py3` instead of `py`. Did you actually try using the plugin with patches applied? I would be surprised if it works! 
2. More importantly, on Ubuntu 16.04 the default Python version is 2.7. If you fire up `python3` in terminal and try to import `rospkg`, the package is not found, because it is installed for a different Python version.

I'd be happy to add macOS support for this plugin, but we will need to come up with something that does not break things for Ubuntu.

**Comment by wkentaro** [comment]
I see. Thanks for pointing out the problem of the second commit. I was trying to skip rosvim on macOS by silently finishing it. 
To make it correctly work, now I understand I should find another solution.

**Comment by taketwo** [comment]
Does macOS actually support ROS with Python 3? I'm not a macOS user, but according to [these instructions](http://wiki.ros.org/kinetic/Installation/OSX/Homebrew/Source) I found, Python 2.7 is used.

**Comment by wkentaro** [comment]
Sorry for confusing you. Actually, I am just using same vim configuration on both Ubuntu14.04 and macOS, and I had this error on macOS since Homebrew migrated to Python3 as default.

**Comment by taketwo** [comment]
I see. So the goal of this PR was to prevent errors/warnings during loading of this plugin on Vim with `+python3`? I suppose with the commit that I cherry-picked from you there should be no errors/warnings anymore. I will close this for now, please reopen if you still experience problems.

**Comment by wkentaro** [comment]
Yeah, that is the goal. However, I still have a warning: `Disabling ros.vim: Vim with +python is required`,
and am thinking how to avoid this warning.

**Comment by wkentaro** [comment]
I found a solution: https://github.com/wkentaro/dotfiles/commit/6cf246d8064266cb45f62de90944df475397e126#diff-81ffc150fe634c808d94679e53aa77e8R22
Thank you for your support.

**Comment by taketwo** [comment]
Generally speaking, I'd like to keep this warning, because silently disabling the plugin can be confusing, especially for new users. I was going to propose to add a config option. But if you already found a suitable solution, then no need. Thanks for using the plugin and contributing!

**Pull request closed without merging**
