### PR TITLE
[WIP] Python3

### PR DESCRIPTION
**Pull request by galou**
@taketwo: can you please have a look at this. I can't find at this point where the difference between Python2 and Python3 is.

By the way `rospkg` is available for Python 3 so there is no reason why Python 3 should not work. But apparently it requires a little bit more work...

### CODE REVIEW

**Comment by taketwo** [comment]
I would like the plugin to keep working out of the box on Ubuntu 16.04. Unfortunately, this means that only Vim 7.4.1689 features can be used. As far as I can tell, `pyx` requires Vim 8.0.0251 or above, so we can not use it.

I haven't tried using ROS with Python 3, but I may have some time this weekend to give it a go.

**Comment by galou** [comment]
Indeed, I installed Vim 8 from PPA on Ubuntu 16. I agree with you with the out-of-the-box compatibility. I just didn't know `pyx` was a Vim 8 feature.
Let's see if I manage to rewrite the commit without `pyx` before you have a look at it...

**Comment by moriarty** [comment]
@taketwo I believe the ROS Melodic (18.04) build farm triggers several other distros, including Debian which defaults to Python3... so there is “better” “support”...

But with 16.04 and earlier support is ¯\_(ツ)_/¯

**Comment by galou** [comment]
With the py3 branch and Python 3 on Ubuntu 16.04 with Kinetic I have the same error as with my python3 branch:
```
Error detected while processing /home/gael/.vim/bundle/.cache/vimrc/.dein/autoload/ros.vim:
line   17:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gael/.vim/bundle/.cache/vimrc/.dein/plugin/rosvim/__init__.py", line 10, in <module>
    from . import filetypes as ft
  File "/home/gael/.vim/bundle/.cache/vimrc/.dein/plugin/rosvim/filetypes/__init__.py", line 8, in <module>
    from . import msg
  File "/home/gael/.vim/bundle/.cache/vimrc/.dein/plugin/rosvim/filetypes/msg.py", line 33, in <module>
    @vimp.function('ros#msg_goto_definition')
  File "/home/gael/.vim/bundle/.cache/vimrc/.dein/plugin/vimp/functions.py", line 44, in decorator
    _functions[function_name] = f if is_function else f()
  File "/home/gael/.vim/bundle/.cache/vimrc/.dein/plugin/rosvim/filetypes/msg.py", line 35, in goto_definition
    text, group, start, end = vimp.syntax.get_entire_syntax_region()
  File "/home/gael/.vim/bundle/.cache/vimrc/.dein/plugin/vimp/syntax.py", line 51, in get_entire_syntax_region
    for p, c in vimp.buf.items(start=seed, reversed=True):
  File "/home/gael/.vim/bundle/.cache/vimrc/.dein/plugin/vimp/buffer.py", line 134, in items
    yield (p, vim.current.buffer[line][col])
IndexError: string index out of range
E117: Unknown function: ros#Rosed
```

With Python 2 your plugin seems to work (I tested only Rosed).
```

**Comment by galou** [comment]
I noticed another error in the py3 branch when used with Python3. First I have to say that this may due to my particular setup. I have a project directory were I store my source code for ROS and I symlinked this directory in my `$ROS_WORKSPACE/src` directory. The problem here is that Vim doesn't open the file `$ROS_WORKSPACE/src/my_package/src/mynode.cpp` but `/path/to/the/project/.../my_package/src/mynode.cpp` which is not in the ROS workspace.

The error I get is 
```
Not a message type
Error detected while processing function <SNR>62_Detect:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
vim.error: Vim(py3):Traceback (most recent call last):
```
when opening a launch file.

By the way, if you know a way to convince Vim to open the file in the symlinked directory, I'd be glad to hear about it.

**Comment by taketwo** [comment]
Closing this since `vim-ros` requires Python 3 now.

**Pull request closed without merging**
